version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:18.3
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql
  backend:
    image: sitkliph/foodgram-backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/collected_static
      - media:/app/media
      - ./data/:/data
    environment:
      DJANGO_DEBUG_MODE: false
  frontend:
    image: sitkliph/foodgram-frontend
    volumes:
      - static:/static
  gateway:
    image: sitkliph/foodgram-gateway
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - 8080:80
    volumes:
      - static:/usr/share/nginx/html/static
      - media:/usr/share/nginx/html/media
