# Generated by Django 6.0.2 on 2026-03-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_carts', 'ordering': ('user__username',), 'verbose_name': 'корзина покупок', 'verbose_name_plural': 'Корзины покупок'},
        ),
    ]
